% This is an autogenerated sample test for file SimulationModel.m
classdef testSimulationModel < matlab.unittest.TestCase

    methods (Test)
        function test_simulate(testCase)
            obj = SimulationModel();

            testCase.verifyEmpty(obj.SimData);

            parameters = [8147.2369,9057.9194,1269.8682,9133.7586,6323.5925,975.40405];
            % Exercise the function obj.simulate
            obj.simulate(parameters);

            testCase.verifyNotEmpty(obj.SimData);
        end
    end
end