% This is an autogenerated sample test for file all
classdef tSimulateModel < matlab.unittest.TestCase
    methods (Test)
        function testSimData(testCase)
            % Specify the input(s) of all
            sObj = SimulationModel;
            simulate(sObj);
            
            output1 = isa(sObj.SimData, 'SimData');
            output2 = all(ismember(sObj.SimData.DataNames,["Drug","Receptor","Complex","RO"]));

            testCase.verifyTrue(output1);
            testCase.verifyTrue(output2);
        end
    end
end